spring:
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8080/realms/my-test-realm
          jwk-set-uri: ${spring.security.oauth2.resourceserver.jwt.issuer-uri}/protocol/openid-connect/certs
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    url: jdbc:mysql://localhost:3306/crud
    password: '607881096'
  servlet:
    multipart:
      max-request-size: 2MB
      max-file-size: 2MB
  jpa:
    database-platform: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto: update
jwt:
  auth:
    converter:
      resource-id: test-client
      principal-attribute: preferred_username

logging:
  level:
    org.springframework.security: DEBUG
server:
  port: '9010'
